Review
luck-o-o-luck/CringeTasks pull request #1
Opened 2021-07-17 12:29 UTC by luck-o-o-luck

2021-07-17 14:35 UTC, annchous requested changes
Будем считать, что это первая итерация. Когда исправишь, пройдусь ещё раз, потому что всё сразу делать будет неудобно и тебе, и мне. Так что жду правочек и ререквест на ревью)

2021-07-17 14:35 UTC, annchous commented on TaskStatus.cs
> +        End
Я бы подумала над неймингом. Например, `Finished`, кмк, более удачно звучит )

2021-07-17 14:35 UTC, annchous commented on tasks.sln
> +﻿
В шарпах принято называть солюшены, проекты, классы и прочее с помощью `PascalCase`. То есть этот файл должен по-правильному должен был называться `Tasks.sln`.

2021-07-17 14:35 UTC, annchous commented on TaskBase.cs
> +        public string Name { get; set; }
Во имя иммутабельности типов предлагаю убрать сеттеры

2021-07-17 14:35 UTC, annchous commented on SaveAndLoad.cs
> +    class SaveAndLoad
Не очень удачный нейминг. Советую вообще не использовать союзы/предлоги в наименовании классов и прочего. Если хочется какой-то пример, то можно было бы назвать `FileHandler`, потому что у тебя тут идёт работа с чтением/записью из/в файл.

2021-07-17 14:35 UTC, annchous commented on SaveAndLoad.cs
> +        public void Load(string path, ref List<Task> task)
Реф это не выход, лучше просто в качестве возвращаемого значения сделай список, так будет удобней и логичней)

2021-07-17 14:35 UTC, annchous commented on SaveAndLoad.cs
> +            if (!File.Exists(path)) return;
Просто `return`?) А что потом?) Лучше сразу дать чётко знать, что что-то пошло не так, например, выкинуть исключение с сообщением о том, что файла по заданному пути не существует!

2021-07-17 14:35 UTC, annchous commented on SaveAndLoad.cs
> +            Console.WriteLine(path);
Не нужно, мне кажется

2021-07-17 14:35 UTC, annchous commented on Delete.cs
> +    class Delete
Для подобных целей лучше выделить общую сущность менеджера задач, в которой можно будет хранить список задач. Туда же можно будет инкапсулировать методы, отвечающие за логику добавления и выполнения задач. А вот для печати на консоль лучше сделать тоже отдельный класс, который будет заниматься именно этим.

2021-07-17 14:35 UTC, annchous commented on Commands.cs
> +            }
```
о
  о
    о
      о
        очень сильная вложенность)
```
Постарайся подумать, что с этим можно придумать. Если не придумаешь - пиши, вместо решим)

2021-07-17 14:35 UTC, annchous commented on Commands.cs
> +        public void AddToGroup(string id, string name, List<GroupTask> t, List<Task> t1)
Не экономь на названиях (это к `t` и `t1`)

2021-07-17 14:35 UTC, annchous commented on Commands.cs
> +        public void AddSubtasks(string id, string name, string idParent, List<Task> tasks)
Скорее `idParent` -> `parentId`

2021-07-17 14:35 UTC, annchous commented on Program.cs
> +        {
Хорошо бы считывание команд с консоли вынести в отдельную сущность. Условимся, что Main нам чисто для запуска, а не отработки какой-то бизнес-логики)

2021-07-17 14:38 UTC, luck-o-o-luck commented on Commands.cs
> +        public void AddToGroup(string id, string name, List<GroupTask> t, List<Task> t1)
Я забыла поменять :с Поняла

2021-07-17 15:45 UTC, luck-o-o-luck commented on TaskBase.cs
> +        public string Name { get; set; }
Немного не понимаю, как без сеттера тогда сделать. Можно сделать его приватным и реализовать метод для присваивания в классе, но нужно ли это? Либо просто при инициализации, но тогда я не понимаю логику совсем. Мне просто кажется, что убирать сеттер не очень удобно. Если я просто захочу поменять саму таску, то что меня должно останавливать? Просто сделать проверку. Ну либо я сейчас совсем ничего не понимаю...

2021-07-18 21:01 UTC, FrediKats commented
![image](https://user-images.githubusercontent.com/22368203/126081999-06a6aeb2-6a00-43b6-8448-ba3ef8c3981b.png)
Будет весело)

2021-07-19 15:31 UTC, annchous requested changes
Переписать на единообразные линки, рассмотреть критические ситуации, которые надо обрабатывать (нет группы с запрошенными именем, etc), следить за неймингом.

2021-07-19 15:31 UTC, annchous commented on TasksDB.cs
> +        private List<GroupTask> groups;
Нейминг приватных полей должен начинаться с нижнего подчёркивания (`_tasks`)

2021-07-19 15:31 UTC, annchous commented on TasksDB.cs
> +    class DB
Плохой нейминг. Во-первых, слишком коротко и непонятно, во-вторых по-шарповому было бы `Db`

2021-07-19 15:31 UTC, annchous commented on TasksDB.cs
> +
Лишняя строка попала

2021-07-19 15:31 UTC, annchous commented on TasksDB.cs
> +        }
Конструктор должен располагаться после полей, но до методов, а не где-то вперемешку со всем

2021-07-19 15:31 UTC, annchous commented on TasksDB.cs
> +        public List<GroupTask> GetfGroup() => groups;
Можно сделать вместо этого и приватных полей просто свойства?
```csharp
public List<Task> Tasks { get; }
```

2021-07-19 15:31 UTC, annchous commented on TasksDB.cs
> +                }
Мб сделать брейк какой-нибудь, чтобы оно как нашло, дальше по листам не шерудило зря?

2021-07-19 15:31 UTC, annchous commented on TasksDB.cs
> +                                   select subTask;
Перепиши на такой же тип линков, как .Select(), .Where() т.д., чтобы всё было в едином стиле

2021-07-19 15:31 UTC, annchous commented on TasksDB.cs
> +            if (check)
Можно без переменной обойтись и сразу .Any() в if вписать

2021-07-19 15:31 UTC, annchous commented on TasksDB.cs
> +            bool check = false;
Флаги - некрасиво. И тут вообще можно обойтись каким-нибудь `return tasks.Any(...)`

2021-07-19 15:31 UTC, annchous commented on TasksDB.cs
> +            if (check)
Можно без флага

2021-07-19 15:31 UTC, annchous commented on TasksDB.cs
> +                                    select subTask;
Переделать на единообразные линки

2021-07-19 15:31 UTC, annchous commented on TasksDB.cs
> +            SearchCompleted();
Это для чего?

2021-07-19 15:31 UTC, annchous commented on TasksDB.cs
> +                Display.PrintGroup(group);
Можно было бы тогда всю логику печати в Display и отправить, не?

2021-07-19 15:31 UTC, annchous commented on TasksDB.cs
> +            }
Как-то... вложенно слишком что ли, можно что-то сделать с этим, наверно

2021-07-19 15:31 UTC, annchous commented on ConsoleIO.cs
> +        public string path;
Зачем эти поля? Можно сразу всё в конструктор закидывать, кмк

2021-07-19 15:31 UTC, annchous commented on ConsoleIO.cs
> +                        bool ch = db.SearchTask(name);
Нейминг `ch`

2021-07-19 15:31 UTC, annchous commented on TasksDB.cs
> +                task.SubTasks.Clear();
А разве если я просто таску удалю, все её сабтаски тоже не исчезнут?)

2021-07-19 15:31 UTC, annchous commented on TasksDB.cs
> +
Что, если группа с заданным именем не будет найдена?

2021-07-19 15:36 UTC, luck-o-o-luck commented on TasksDB.cs
> +            SearchCompleted();
При выводе ищет выполненные подзадачи для задачи. Возможно, лучше переписать.

2021-07-20 12:17 UTC, FrediKats requested changes
Я мимо проходил, только первый файл посмотрел :3

2021-07-20 12:17 UTC, FrediKats commented on ConsoleIO.cs
> +        private TaskDataStore _mockData = new TaskDataStore();
А это точно мок?

2021-07-20 12:17 UTC, FrediKats commented on ConsoleIO.cs
> +            for (int i = 1; i < args.Length; i++)
А зачем тут for?

2021-07-20 12:17 UTC, FrediKats commented on ConsoleIO.cs
> +            string Date;
Зачем?

2021-07-20 12:17 UTC, FrediKats commented on ConsoleIO.cs
> +                        catch (Exception ep)
Дублируется. Лучше делать трай кетч не в кейса, а обернуть весь свитч.

2021-07-20 12:17 UTC, FrediKats commented on ConsoleIO.cs
> +                        _mockData.Load(@args[0]);
Лоад выглядит странно. Кажется, что он должен загружать и возвращать загруженные данные, а не изменять объект (сейчас же так происходи, да?)

2021-07-20 12:59 UTC, luck-o-o-luck commented on ConsoleIO.cs
> +            for (int i = 1; i < args.Length; i++)
Немного не поняла. По сути, я прохожусь по всем аргументам, поэтому тут for. Если вопрос заключается в том, почему не foreach, то это уже другой разговор.

2021-07-20 13:01 UTC, luck-o-o-luck commented on ConsoleIO.cs
> +            string Date;
The devils going to make me a free man. А на самом деле для моего удобства. Но это тоже можно исправить. Я использовала для ввода дедлайна.

2021-07-20 19:15 UTC, annchous requested changes

2021-07-20 19:15 UTC, annchous commented on GroupTasks.cs
> +        public string Name { get; set; }
Сеттер убрать и добавить конструктор (вместо сеттера пользоваться для инициализации конструктором). И название у класса странноватое или не в том порядке слова разложены 🤔

2021-07-20 19:15 UTC, annchous commented on SubTask.cs
> +        public Task ParentTask { get; set; }
Не используется (кажется)?

2021-07-20 19:15 UTC, annchous commented on TaskDataStore.cs
> +        public bool SearchTask(string name) => _tasks.Any(task => task.Name.ToLower() == name.ToLower());
Мне не очень нравится нейминг с `Search` для методов, возвращающих `bool` 🤔 Мб что-то с `exists` сделать

2021-07-20 19:15 UTC, annchous commented on TaskDataStore.cs
> +                Id = _tasks.Count + 1
Почему именно такая инициализация, а не через конструктор?

2021-07-20 19:15 UTC, annchous commented on TaskDataStore.cs
> +        public void AddGroup (string name)
```suggestion
        public void AddGroup(string name)
```

2021-07-20 19:15 UTC, annchous commented on TaskDataStore.cs
> +                foreach (Task task in completedTask)
А что, могут/должны найтись 2 таски с одним айди?

2021-07-20 19:15 UTC, annchous commented on TaskDataStore.cs
> +                task.Completed = task.SubTasks.Count(subTask => subTask.Status == TaskStatus.Finished);
Можно не делать это каждый раз, а вынести в поле просто по типу
```csharp
public bool Completed => SubTasks.Count(subTask => subTask.Status == TaskStatus.Finished);
```

2021-07-20 19:15 UTC, annchous commented on TaskDataStore.cs
> +            foreach (GroupTask group in selectedGroup)
Аналогичный вопрос про группы с одинаковым именем

2021-07-20 19:15 UTC, annchous commented on TaskDataStore.cs
> +            foreach (Task task in selectedTask)
А что, могут/должны найтись 2 таски с одним айди?

2021-07-20 19:15 UTC, annchous commented on TaskDataStore.cs
> +                });
Почему не в обычном конструкторе инициализировать?

2021-07-20 19:15 UTC, annchous commented on TaskDataStore.cs
> +            }
Хотелось бы, чтобы `TaskDataStore` не отвечал за вывод на консоль всё-таки. Что можно сделать: этот метод пусть возвращает список всех задач, у которых сегодня дедлайн. А дисплей этот список принимает и печатает.

2021-07-20 19:15 UTC, annchous commented on Display.cs
> +        public static void PrintAll (List <Task> tasks, List <GroupTask> groups)
```suggestion
        public static void PrintAll(List <Task> tasks, List <GroupTask> groups)
```

2021-07-20 19:15 UTC, annchous commented on Display.cs
> +                PrintGroup(group);
Тут дважды задачи не распечатаются разве? Сначала те, которые в общем списке задач, а потом ещё раз те, которые в группе "состоят" (?)

2021-07-20 19:20 UTC, annchous commented on TaskDataStore.cs
> +                foreach (Task task in completedTask)
Если что, в LINQ есть метод `.Single(predicate)`, который просигналит эксепшеном, если найдёт более двух или менее одного результата, соответствующего предикату, но при благоприятных обстоятельствах вернёт только одну нужную ссылку на объект (что тебе, кажется, и надо?).

2021-07-21 19:14 UTC, annchous approved these changes

2021-08-26 21:41 UTC, merged